language: java
install: ant
jdk:
  - openjdk7
  - oraclejdk7
  
after_success:
  - chmod 600 .travis/deployment_key # this key should have push access
  - eval `ssh-agent -s`
  - ssh-add .travis/deployment_key
  - ssh-add -l #verify key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "fabiojose@gmail.com"
  - git config --global user.name "fabiojose"
  - git remote add deploy git@github.com:fabiojose/javaf.git
  - git add dist
  - git commit -am "Travis CI Success Jar"
  - git push deploy