//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 10:07:25 AM BRT 
//


package bradesco.tf.validate;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventValidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventValidator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bradesco.com.br/firp}Event">
 *       &lt;choice>
 *         &lt;element name="validator-id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="validator" type="{http://www.bradesco.com.br/firp}Validator" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventValidator", propOrder = {
    "validatorId",
    "validator"
})
public class EventValidator
    extends Event
{

    @XmlElement(name = "validator-id")
    protected List<String> validatorId;
    protected List<Validator> validator;

    /**
     * Gets the value of the validatorId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validatorId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidatorId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidatorId() {
        if (validatorId == null) {
            validatorId = new ArrayList<String>();
        }
        return this.validatorId;
    }

    /**
     * Gets the value of the validator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Validator }
     * 
     * 
     */
    public List<Validator> getValidator() {
        if (validator == null) {
            validator = new ArrayList<Validator>();
        }
        return this.validator;
    }

}
