//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.javaf.model.ValuePlace;

/**
 * <p>Java class for MaximumLengthValidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaximumLengthValidator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bradesco.com.br/firp}Validator">
 *       &lt;sequence>
 *         &lt;element name="maximum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="value-place" type="{http://www.bradesco.com.br/firp}ConfigurePlace"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaximumLengthValidator", propOrder = {
    "maximum",
    "valuePlace"
})
public class MaximumLengthValidator
    extends Validator implements IValidator
{

	protected int maximum;
    @XmlElement(name = "value-place", required = true, type = ConfigurePlace.class)
    protected ValuePlace<String> valuePlace;
    
    public MaximumLengthValidator(){
    	
    }
    
    public MaximumLengthValidator(final int maxImum, final ValuePlace<String> valuePlace){
    	setMaximum(maximum);
    	setValuePlace(valuePlace);
    }

    /**
     * Gets the value of the maximum property.
     * 
     */
    public int getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     */
    public void setMaximum(int value) {
        this.maximum = value;
    }

    /**
     * Gets the value of the valuePlace property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurePlace }
     *     
     */
    public ValuePlace<String> getValuePlace() {
        return valuePlace;
    }

    /**
     * Sets the value of the valuePlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurePlace }
     *     
     */
    public void setValuePlace(ValuePlace<String> value) {
        this.valuePlace = value;
    }
    
	public boolean validate(List<String> messages) {
		
		boolean _result = Boolean.TRUE;
		final String _value = uformat.toString(valuePlace.getValue());
		
		_result = !(_value.length() > maximum);
		if(!_result){
			messages.add(helper.onInvalid(this, valuePlace.getLabel() + " possui comprimento superior ao limite de " + maximum + ": " + _value.length()));
			
			helper.onInvalid(this, valuePlace);
		}
		return _result;
	}

}
