//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.javaf.model.ValuePlace;

/**
 * <p>Java class for MinimumIntegerValidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MinimumIntegerValidator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bradesco.com.br/firp}Validator">
 *       &lt;sequence>
 *         &lt;element name="minimum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="value-place" type="{http://www.bradesco.com.br/firp}ConfigurePlace"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MinimumIntegerValidator", propOrder = {
    "minimum",
    "valuePlace"
})
public class MinimumIntegerValidator
    extends Validator implements IValidator
{

	protected int minimum;
    @XmlElement(name = "value-place", required = true, type = ConfigurePlace.class)
    protected ValuePlace<Integer> valuePlace;
    
    public MinimumIntegerValidator(){
    	
    }
    
    public MinimumIntegerValidator(final int minimum, final ValuePlace<Integer> valuePlace){
    	setMinimum(minimum);
    	setValuePlace(valuePlace);
    }

    /**
     * Gets the value of the minimum property.
     * 
     */
    public int getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     */
    public void setMinimum(int value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the valuePlace property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurePlace }
     *     
     */
    public ValuePlace<Integer> getValuePlace() {
        return valuePlace;
    }

    /**
     * Sets the value of the valuePlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurePlace }
     *     
     */
    public void setValuePlace(ValuePlace<Integer> value) {
        this.valuePlace = value;
    }

	public boolean validate(List<String> messages) {

		boolean _result = Boolean.TRUE;
		final int _value = uformat.toInteger(valuePlace.getValue());
		
		if(_value <= minimum){
			messages.add(helper.onInvalid(this, valuePlace.getLabel() + " deve possuir um valor maior que " + minimum));
			
			helper.onInvalid(this, valuePlace);
			
			_result = Boolean.FALSE;
		}
		
		return _result;
	}

}
