//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.javaf.model.ValuePlace;

/**
 * <p>Java class for NotAddedItemValidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotAddedItemValidator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bradesco.com.br/firp}Validator">
 *       &lt;sequence>
 *         &lt;element name="value-place" type="{http://www.bradesco.com.br/firp}ConfigurePlace"/>
 *         &lt;element name="add-length">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotAddedItemValidator", propOrder = {
    "valuePlace",
    "addLength"
})
public class NotAddedItemValidator
    extends Validator implements IValidator
{

	@XmlElement(name = "value-place", required = true, type = ConfigurePlace.class)
    protected ValuePlace<List<? extends Object>> valuePlace;
    @XmlElement(name = "add-length")
    protected int addLength;

    /**
     * Gets the value of the valuePlace property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurePlace }
     *     
     */
    public ValuePlace<List<? extends Object>> getValuePlace() {
        return valuePlace;
    }

    /**
     * Sets the value of the valuePlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurePlace }
     *     
     */
    public void setValuePlace(ValuePlace<List<? extends Object>> value) {
        this.valuePlace = value;
    }

    /**
     * Gets the value of the addLength property.
     * 
     */
    public int getAddLength() {
        return addLength;
    }

    /**
     * Sets the value of the addLength property.
     * 
     */
    public void setAddLength(int value) {
        this.addLength = value;
    }

	public boolean validate(final List<String> messages) {

		boolean _result = Boolean.TRUE;
		if(getValuePlace().getValue().size() < getAddLength()){
			messages.add(helper.onInvalid(this, "Deve haver ao menos " + getAddLength() + " item(ns) em " + getValuePlace().getLabel()));
			
			helper.onInvalid(this, getValuePlace());
			
			_result = Boolean.FALSE;
		}
		
		return _result;
	}

}
