//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.javaf.Constants.I18N;
import com.javaf.Constants.INTEGER;
import com.javaf.Constants.STRING;
import com.javaf.model.ValuePlace;

/**
 * <p>Java class for NotFilledValidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotFilledValidator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bradesco.com.br/firp}Validator">
 *       &lt;sequence>
 *         &lt;element name="value-place" type="{http://www.bradesco.com.br/firp}ConfigurePlace" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotFilledValidator", propOrder = {
    "valuePlace"
})
public class NotFilledValidator
    extends Validator implements IValidator
{

	@XmlElement(name = "value-place", required = true, type = ConfigurePlace.class)
    protected List<ValuePlace<? extends Object>> valuePlace;
    
    public NotFilledValidator(){
    
    }
    
    public NotFilledValidator(final ValuePlace<? extends Object>...valuePlace){
    	getValuePlace().addAll(Arrays.asList(valuePlace));
    }

    /**
     * Gets the value of the valuePlace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuePlace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuePlace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurePlace }
     * 
     * 
     */
    public List<ValuePlace<? extends Object>> getValuePlace() {
        if (valuePlace == null) {
            valuePlace = new ArrayList<ValuePlace<? extends Object>>();
        }
        return this.valuePlace;
    }
    
    public void setValuePlace(final List<ValuePlace<? extends Object>> valuePlace){
    	this.valuePlace = valuePlace;
    }

	public boolean validate(List<String> messages) {
		
		boolean _result = Boolean.TRUE;
		final List<String> _messages = new ArrayList<String>();
		for(ValuePlace<? extends Object> _field : valuePlace){
			
			final String _value     = uformat.toString(_field.getValue());
			final boolean _isValid = (null!= _field.getValue() && !_value.trim().equals(STRING.EMPTY));
			if(!_isValid){
				_messages.add(STRING.HIFEM + STRING.SPACE1 + _field.getLabel());
				
				helper.onInvalid(this, _field);
			}
			_result &= _isValid;
		}
		
		if(_messages.size() > INTEGER._0){
			if(uformat.toString(getMessage()).equals(STRING.EMPTY)){ 
				
				messages.add(localization.localize(I18N.PREENCHER));
				messages.addAll(_messages);
				
			} else {
				messages.add(getMessage());
			}
			
		}
		
		return _result;
	}

}
