//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.javaf.Constants.I18N;
import com.javaf.Constants.INTEGER;
import com.javaf.Constants.STRING;
import com.javaf.model.ValuePlace;

/**
 * <p>Java class for NotSelectedRadioValidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotSelectedRadioValidator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bradesco.com.br/firp}Validator">
 *       &lt;sequence>
 *         &lt;element name="value-place" type="{http://www.bradesco.com.br/firp}ConfigurePlace" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotSelectedRadioValidator", propOrder = {
    "valuePlace"
})
public class NotSelectedRadioValidator
    extends Validator implements IValidator
{

	@XmlElement(name = "value-place", required = true, type = ConfigurePlace.class)
    protected List<ValuePlace<Boolean>> valuePlace;
    
    public NotSelectedRadioValidator(){
    	
    }
    
    public NotSelectedRadioValidator(final ValuePlace<Boolean>...valuePlace){
    	getValuePlace().addAll(Arrays.asList(valuePlace));
    }

    /**
     * Gets the value of the valuePlace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuePlace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuePlace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurePlace }
     * 
     * 
     */
    public List<ValuePlace<Boolean>> getValuePlace() {
        if (valuePlace == null) {
            valuePlace = new ArrayList<ValuePlace<Boolean>>();
        }
        return this.valuePlace;
    }
    
    public void setValuePlace(final List<ValuePlace<Boolean>> valuePlace){
    	this.valuePlace = valuePlace;
    }

	public boolean validate(List<String> messages) {
		
		boolean _result = Boolean.FALSE;
		final List<String> _messages = new ArrayList<String>();
		
		for(ValuePlace<Boolean> _radio : valuePlace){
			
			final boolean _isSelected = _radio.getValue();
			if(!_isSelected){
				_messages.add(helper.onInvalid(this, STRING.HIFEM + _radio.getLabel()));
				
				helper.onInvalid(this, _radio);
			}
			
			_result |= _isSelected;
		}
		
		if(_messages.size() > INTEGER._0 && !_result){
			messages.add(localization.localize(I18N.SELECIONAR_UMA_DAS_OPCOES));
			messages.addAll(_messages);
		}
		
		return _result;
	}

}
