//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.bradesco.firp.common.util.application package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Application_QNAME = new QName("http://www.bradesco.com.br/firp", "application");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.bradesco.firp.common.util.application
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Validation }
     * 
     */
    public Validation createValidation() {
        return new Validation();
    }

    /**
     * Create an instance of {@link NotSelectedCheckboxValidator }
     * 
     */
    public NotSelectedCheckboxValidator createNotSelectedCheckboxValidator() {
        return new NotSelectedCheckboxValidator();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

    /**
     * Create an instance of {@link Validators }
     * 
     */
    public Validators createValidators() {
        return new Validators();
    }

    /**
     * Create an instance of {@link Validations }
     * 
     */
    public Validations createValidations() {
        return new Validations();
    }

    /**
     * Create an instance of {@link NotSelectedRadioValidator }
     * 
     */
    public NotSelectedRadioValidator createNotSelectedRadioValidator() {
        return new NotSelectedRadioValidator();
    }

    /**
     * Create an instance of {@link NotFilledValidator }
     * 
     */
    public NotFilledValidator createNotFilledValidator() {
        return new NotFilledValidator();
    }

    /**
     * Create an instance of {@link NotSelectedItemValidator }
     * 
     */
    public NotSelectedItemValidator createNotSelectedItemValidator() {
        return new NotSelectedItemValidator();
    }

    /**
     * Create an instance of {@link MinimumIntegerValidator }
     * 
     */
    public MinimumIntegerValidator createMinimumIntegerValidator() {
        return new MinimumIntegerValidator();
    }

    /**
     * Create an instance of {@link ConfigurePlace }
     * 
     */
    @SuppressWarnings("unchecked")
	public ConfigurePlace createConfigurePlace() {
        return new ConfigurePlace();
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link Views }
     * 
     */
    public Views createViews() {
        return new Views();
    }

    /**
     * Create an instance of {@link NotAddedItemValidator }
     * 
     */
    public NotAddedItemValidator createNotAddedItemValidator() {
        return new NotAddedItemValidator();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link DateNotLessThanAnotherValidator }
     * 
     */
    public DateNotLessThanAnotherValidator createDateNotLessThanAnotherValidator() {
        return new DateNotLessThanAnotherValidator();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link MaximumLengthValidator }
     * 
     */
    public MaximumLengthValidator createMaximumLengthValidator() {
        return new MaximumLengthValidator();
    }

    /**
     * Create an instance of {@link Validator }
     * 
     */
    public Validator createValidator() {
        return new Validator();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Application }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bradesco.com.br/firp", name = "application")
    public JAXBElement<Application> createApplication(Application value) {
        return new JAXBElement<Application>(_Application_QNAME, Application.class, null, value);
    }

}
