//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bradesco.com.br/firp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bradesco.tf.validate;
