//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.30 at 04:48:55 PM BRST 
//


package bradesco.tf.validate;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pesquisar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pesquisar">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filtro-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resultado-property" type="{http://www.bradesco.com.br/firp}Property" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pesquisar", propOrder = {
    "filtroClass",
    "resultadoProperty"
})
public class Pesquisar {

    @XmlElement(name = "filtro-class", required = true)
    protected String filtroClass;
    @XmlElement(name = "resultado-property")
    protected List<Property> resultadoProperty;

    /**
     * Gets the value of the filtroClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiltroClass() {
        return filtroClass;
    }

    /**
     * Sets the value of the filtroClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiltroClass(String value) {
        this.filtroClass = value;
    }

    /**
     * Gets the value of the resultadoProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultadoProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultadoProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getResultadoProperty() {
        if (resultadoProperty == null) {
            resultadoProperty = new ArrayList<Property>();
        }
        return this.resultadoProperty;
    }

}
