//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 11:59:27 AM BRT 
//


package bradesco.tf.validate;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.javaf.model.ValuePlace;

/**
 * <p>Java class for TimePeriodValidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimePeriodValidator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bradesco.com.br/firp}DateNotLessThanAnotherValidator">
 *       &lt;sequence>
 *         &lt;element name="determinado" type="{http://www.bradesco.com.br/firp}ConfigurePlace"/>
 *         &lt;element name="indeterminado" type="{http://www.bradesco.com.br/firp}ConfigurePlace"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimePeriodValidator", propOrder = {
    "determinado",
    "indeterminado"
})
public class TimePeriodValidator
    extends DateNotLessThanAnotherValidator
{

    @XmlElement(required = true, type = ConfigurePlace.class)
    protected ValuePlace<Boolean> determinado;
    @XmlElement(required = true, type = ConfigurePlace.class)
    protected ValuePlace<Boolean> indeterminado;

    /**
     * Gets the value of the determinado property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurePlace }
     *     
     */
    public ValuePlace<Boolean> getDeterminado() {
        return determinado;
    }

    /**
     * Sets the value of the determinado property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurePlace }
     *     
     */
    public void setDeterminado(ValuePlace<Boolean> value) {
        this.determinado = value;
    }

    /**
     * Gets the value of the indeterminado property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurePlace }
     *     
     */
    public ValuePlace<Boolean> getIndeterminado() {
        return indeterminado;
    }

    /**
     * Sets the value of the indeterminado property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurePlace }
     *     
     */
    public void setIndeterminado(ValuePlace<Boolean> value) {
        this.indeterminado = value;
    }

    
    public boolean validate(List<String> messages) {
		boolean _result = Boolean.TRUE;
	
		if(getDeterminado().getValue()){
			_result = super.validate(messages);
		}
		
		return _result;
    }
}
