//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Validation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Validation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="load-policy">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ON-DEMAND"/>
 *               &lt;enumeration value="EAGER"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="validator" type="{http://www.bradesco.com.br/firp}Validator"/>
 *           &lt;element name="validator-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Validation", propOrder = {
    "loadPolicy",
    "validator",
    "validatorId"
})
public class Validation {

    @XmlElement(name = "load-policy", required = true)
    protected String loadPolicy;
    protected Validator validator;
    @XmlElement(name = "validator-id")
    protected String validatorId;

    /**
     * Gets the value of the loadPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadPolicy() {
        return loadPolicy;
    }

    /**
     * Sets the value of the loadPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadPolicy(String value) {
        this.loadPolicy = value;
    }

    /**
     * Gets the value of the validator property.
     * 
     * @return
     *     possible object is
     *     {@link Validator }
     *     
     */
    public Validator getValidator() {
        return validator;
    }

    /**
     * Sets the value of the validator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validator }
     *     
     */
    public void setValidator(Validator value) {
        this.validator = value;
    }

    /**
     * Gets the value of the validatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidatorId() {
        return validatorId;
    }

    /**
     * Sets the value of the validatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidatorId(String value) {
        this.validatorId = value;
    }

}
