//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.javaf.javase.logging.ILogging;
import com.javaf.javase.logging.Logging;
import com.javaf.javase.text.UtilFormat;
import com.javaf.javase.util.ILocalization;
import com.javaf.javase.util.Localization;

/**
 * <p>Java class for Validator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Validator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Validator", propOrder = {
    "message"
})
@XmlSeeAlso({
	MinimumIntegerValidator.class,
    MaximumLengthValidator.class,
    NotFilledValidator.class,
    NotSelectedCheckboxValidator.class,
    NotSelectedItemValidator.class,
    DateNotLessThanAnotherValidator.class,
    MinimumFloatValidator.class,
    NotSelectedRadioValidator.class,
    NotAddedItemValidator.class
})
public class Validator implements IValidator{

    protected String message;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean validate(List<String> messages) {
		throw new UnsupportedOperationException();
	}

	private transient boolean turnedOn;
	public boolean isTurnedOn(){
		return turnedOn;
	}
	public void setTurnedOn(final boolean turnedOn){
		this.turnedOn = turnedOn;
	}
	
	private transient String first;
	public String getFirst() {
		return first;
	}
	
	public void setFirst(final String first){
		this.first = first;
	}
	
	protected transient final ValidatorHelper helper     = new ValidatorHelper();
	protected transient final UtilFormat uformat         = UtilFormat.getInstance();
	protected transient final ILocalization localization = Localization.getInstance();
	protected transient final ILogging logging           = Logging.loggerOf(getClass());
}
