//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.15 at 09:18:59 AM BRT 
//


package bradesco.tf.validate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for View complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="View">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="view-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="validations" type="{http://www.bradesco.com.br/firp}Validations" minOccurs="0"/>
 *           &lt;element name="validations-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "View", propOrder = {
    "viewClass",
    "validations",
    "validationsId"
})
public class View {

    @XmlElement(name = "view-class", required = true)
    protected String viewClass;
    protected Validations validations;
    @XmlElement(name = "validations-id")
    protected String validationsId;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the viewClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewClass() {
        return viewClass;
    }

    /**
     * Sets the value of the viewClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewClass(String value) {
        this.viewClass = value;
    }

    /**
     * Gets the value of the validations property.
     * 
     * @return
     *     possible object is
     *     {@link Validations }
     *     
     */
    public Validations getValidations() {
        return validations;
    }

    /**
     * Sets the value of the validations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validations }
     *     
     */
    public void setValidations(Validations value) {
        this.validations = value;
    }

    /**
     * Gets the value of the validationsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationsId() {
        return validationsId;
    }

    /**
     * Sets the value of the validationsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationsId(String value) {
        this.validationsId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
